config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :articles do
    member do
      get :likes_summary
    end
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end

  namespace :admin do
    root 'articles#index'
    resources :articles, :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { minimum: 5 }
  validate :title_changes
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :users, through: :likes

  belongs_to :author, class_name: 'User'
  scope :top_commented, -> { order(comments_count: :desc).limit(1) }
  def tags=(value)
    value = sanitize_tags(value) if value.is_a?(String)
    super(value)
  end

  private

  def title_changes
    if title_changed? && persisted? && created_at < 7.days.ago
      errors.add(:title, "cannot be changed")
    end
  end

  def sanitize_tags(text)
    text.downcase.split.uniq
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article, counter_cache: true
  validates :commenter, presence: true, email: true
  validates :body, presence: true, length: { in: 6..500 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true

  validates :user, uniqueness: { scope: :article, message: 'already liked' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, foreign_key: :author_id
  has_many :likes
  has_many :liked_articles, through: :likes, source: :article
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::BaseController
    def index; end
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout "admin"

    http_basic_authenticate_with name: "dhh", password: "secret"

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: %i[show update edit destroy likes_summary]
  before_action :authorize_article, only: %i[edit update destroy]

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result.includes(:author).page(params[:page])
    @top_commented_article = Article.top_commented.first
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(permitted_attributes(Article))
    @article.author = current_user
    if @article.save
      flash[:notice] = 'Your article has been saved'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @comment = @article.comments.build(commenter: session[:commenter])
    @like = Like.find_or_initialize_by(article: @article, user: current_user)

    respond_to do |format|
      format.html do
        @article.increment!(:views_count)
        render
      end
      format.json do
        render json: {
          id: @article.id,
          likes: @article.likes_count,
          comments: @article.comments_count
        }
      end
    end
  end

  def edit; end

  def update
    if @article.update(permitted_attributes(@article))
      flash[:notice] = 'Your article has been saved'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Your article has been deleted'
    redirect_to articles_path
  end

  def likes_summary
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def authorize_article
    authorize @article
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @like = Like.find_or_initialize_by(article: @article, user: current_user)

    if @comment.save
      session[:commenter] = @comment.commenter
      flash[:notice] = 'Your comment has been saved'
      redirect_to article_path(@article)
    else
      render 'articles/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Your comment has been deleted'
    redirect_to article_path(@comment.article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.new(article_id: params[:article_id], user: current_user)
    like.save

    redirect_to article_path(like.article)
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy

    redirect_to article_path(like.article)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def liked_message(model)
    pluralization = pluralize(model.likes_count, 'person')
    message =  "liked this #{model.class.name.downcase}"
    "#{pluralization} #{message}"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/articles/index.html.erb
Artykuły

app/views/articles/_form.html.erb
<%= render 'shared/errors', model: @article %>

<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control", placeholder: "Text" %>
  </div>
  <div class="form-group">
    <%= f.label :tags %>
    <%= f.text_field :tags, class: "form-control", placeholder: "Tags" %>
  </div>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit class: "btn btn-default" %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>List of articles</h1>

<%= search_form_for @q do |f| %>
  <%= f.label :title_cont %>
  <%= f.search_field :title_cont %>

  <%= f.label :text_cont %>
  <%= f.search_field :text_cont %>

  <%= f.label :author_id_eq %>
  <%= f.select :author_id_eq, options_from_collection_for_select(User.all, "id", "email", @q.author_id_eq), include_blank: true %>
  <%= f.submit %>
<% end %>

<h1>TOP COMMENTED!!!!!!!!</h1>
<%= link_to @top_commented_article.title, article_path(@top_commented_article.id) %>

<h2><%= link_to "New article", new_article_path %></h2>
<table class="table">
  <thead>
    <tr>
      <th><%= sort_link(@q, :id) %></th>
      <th><%= sort_link(@q, :title) %></th>
      <th><%= sort_link(@q, :text) %></th>
      <th><%= sort_link(@q, :author_id) %></th>
      <th><%= sort_link(@q, :comments_count) %></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= article.author.email %></td>
        <td id="summary-<%= article.id %>">Comments: <%= article.comments_count %></td>
        <td><%= link_to "Summary", article_path(article, format: :json), class: "btn btn-info summary" %></td>
        <td><%= link_to "Show", article_path(article), class: "btn btn-info" %></td>
        <td>
          <% if policy(article).edit? %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-warning" %>
          <% end %>
        </td>
        <td>
          <% if policy(article).destroy? %>
            <%= link_to "Destroy", article_path(article),
                class: "btn btn-danger",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

<h2><%= link_to "New article", new_article_path %></h2>

app/views/articles/likes_summary.html.erb
<h1> Likes Summary</h1>

<ul>
<% @article.likes.each do |like| %>
  <li>User <%= like.user.email %> liked this article at <%= like.created_at %></li>
<% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <%= image_tag @article.image.url %>
</p>
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<p>
  <strong>Author:</strong>
  <%= @article.author.email %>
</p>
<p>
  <strong>Views count:</strong>
  <%= @article.views_count %>
</p>
<p>
  <strong>Tags:</strong>
  <% @article.tags.each do |tag| %>
      <%= link_to articles_path(q: tag), style: 'margin-left: 4px' do %>
        <span class="label label-info">
          <%= tag %>
        </span>
      <% end %>
  <% end %>
</p>
<p>
  <strong>Created at:</strong>
  <%= @article.created_at %>
</p>
<p>
  <strong>Updated at:</strong>
  <%= @article.updated_at %>
</p>

<%= liked_message(@article) %>
<%= link_to "Likes Summary", likes_summary_article_path(@article) %>
<% if @like.persisted? %>
  <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
  <%= link_to "Unlike", article_like_path(@article, @like), method: :delete %>
<% else %>
  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
  <%= link_to "Like", article_likes_path(@article), method: :post %>
<% end %>

<%= render 'comments/form' %>

<h2>Comments</h2>
<a href="#" id="toggle-comments">HIDE comments</a>
<div id="comments">
  <%= render @article.comments.reload %>
</div>
<%= link_to "Back", articles_path %>
<%= link_to "Edit", edit_article_path(@article) %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Body:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to "Destroy", article_comment_path(comment.article, comment),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= render 'shared/errors', model: @comment %>

<%= form_for([@article, @comment]) do |f| %>
  <div class="form-group">
    <%= f.label :commenter %>
    <%= f.text_field :commenter, class: "form-control", placeholder: "Commenter" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", placeholder: "Body" %>
  </div>
  <p>
    <%= f.submit class: "btn btn-default" %>
  </p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panel Admina</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>

    <h1>Witaj adminie</h1>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>

    <% if current_user %>
      <p>
        Hello <%= current_user.email %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </p>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <h2>Errors!</h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<h1><%= link_to "My blog", articles_path %></h1>